# This is a config for E2B sandbox template.
# You can use template ID (uzoy7e7wwv1tvib8ep6k) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("uzoy7e7wwv1tvib8ep6k") # Sync sandbox
# sandbox = await AsyncSandbox.create("uzoy7e7wwv1tvib8ep6k") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('uzoy7e7wwv1tvib8ep6k')

team_id = "e77529dc-cac4-4449-a4e9-33d9b94d7f02"
dockerfile = "e2b.Dockerfile"
template_id = "uzoy7e7wwv1tvib8ep6k"
