# This is a config for E2B sandbox template.
# You can use template ID (agrlcfpcd4qxe7ly7xro) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("agrlcfpcd4qxe7ly7xro") # Sync sandbox
# sandbox = await AsyncSandbox.create("agrlcfpcd4qxe7ly7xro") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('agrlcfpcd4qxe7ly7xro')

team_id = "e77529dc-cac4-4449-a4e9-33d9b94d7f02"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "agrlcfpcd4qxe7ly7xro"
